# Generated by Django 5.0.2 on 2024-03-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroFinanceiro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14)),
                ('valor', models.CharField(max_length=20)),
                ('data_pagamento', models.DateField()),
                ('forma_pagamento', models.TextField(max_length=50)),
                ('chave_seguranca', models.TextField(max_length=50)),
                ('departamento', models.TextField(max_length=50)),
                ('descricao', models.TextField(default='Serviço sem descrição.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=225)),
                ('cep', models.CharField(max_length=20)),
                ('endereco', models.TextField(max_length=225)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.TextField(max_length=100)),
                ('bairro', models.TextField(max_length=36)),
                ('cidade', models.TextField(max_length=36)),
                ('estado', models.TextField(max_length=36)),
                ('telefone_principal', models.CharField(max_length=14)),
                ('email', models.TextField(max_length=100)),
            ],
        ),
    ]
