# Generated by Django 5.0.6 on 2024-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pronct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrofinanceiro',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone_principal',
            field=models.CharField(max_length=16),
        ),
        migrations.AddField(
            model_name='clientes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
